version: '3.8'

networks:
  polly:
    name: polly-network

services:
  prometheus:
    build: 
      context: ./prometheus
    ports:
      - 9090:9090
    networks:
      - polly

  grafana:
    build: 
      context: ./grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - polly
  
  otel-collector:
    image: otel/opentelemetry-collector:0.73.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" 
      - "8889:8889" 
      - "13133:13133"
      - "4317:4317"
    networks:
      - polly

  app:
    build:
      context: ./dotnet
    depends_on:
      - otel-collector
    ports:
      - 5001:8080
    environment:
      TypiCodeBaseUri: https://jsonplaceholder.typicode.com/
      OtlpEndpointUri: http://otel-collector:4317
    networks:
      - polly
  
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes:
      - ./postgres/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 5432:5432
    networks:
      - polly